# Generated by Django 2.0.4 on 2018-04-30 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_journal_written_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='written_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
